name: today_task
description: "A simple parent-child task management app using Firebase."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Utility
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # State Management (Riverpod)
  flutter_riverpod: ^2.6.1

  # Firebase
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_messaging: ^15.2.1

  # Local Storage & Device Info
  shared_preferences: ^2.5.3
  device_info_plus: ^11.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
